### ISSUE TITLE
error: language item required, but not found: `eh_personality`

### ISSUE THREAD

**Issue by apeng2012** [BlackbirdHQ/atat#101]
cargo test

cargo test -- response

cargo test -- response --target thumbv7em-none-eabi

   Compiling atat v0.11.1 (D:\GPS-rs\atat\atat)
error: language item required, but not found: `eh_personality`

error: language item required, but not found: `eh_personality`

error: aborting due to previous error

error: could not compile `atat`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: build failed

**Comment by MathiasKoch** [comment]
Try with `cargo test --lib`

**Comment by apeng2012** [comment]
Forgive my ignorance

**Comment by MathiasKoch** [comment]
No worries! Ask away :)
