### ISSUE TITLE
Re-exporting of types used in Clock

### ISSUE THREAD

**Issue by dbrgn** [BlackbirdHQ/atat#118]
The `Clock` type is a re-export of `fugit_timer::Timer`. This is a nice convenience feature (because I don't need to depend on `fugit`), but if I actually want to implement the timer trait, I also need access to other types, namely [fugit::Instant](https://docs.rs/fugit/0.3.3/fugit/struct.Instant.html) and [fugit::Duration](https://docs.rs/fugit/0.3.3/fugit/struct.Duration.html).

I'd suggest either moving the `Clock` trait to a separate module and re-exporting Instant and Duration in that module as well (e.g. `atat::clock::{Clock, Instant, Duration}` or alternatively re-exporting `fugit` at the top level.

**Comment by MathiasKoch** [comment]
Both of those approaches sounds reasonable to me.
