### ISSUE TITLE
Naming of ATATCommand::as_str

### ISSUE THREAD

**Issue by dbrgn** [BlackbirdHQ/atat#22]
Since it returns a stack-allocated `heapless::String` and not a `&str`, it should probably be called `as_string`. Otherwise, if you actually wanted a `&str`, you'd have to call `cmd.as_str().as_str()` which is a bit weird :slightly_smiling_face: 

An alternative would be `as_text()` or `text()`, not sure if you'd like that better. I think I'd prefer `as_string()`.

**Comment by MathiasKoch** [comment]
I have changed it locally now, so it will be part of the next release :)
