### ISSUE TITLE
Fails to parse responses without whitespace

### ISSUE THREAD

**Issue by stephanh** [BlackbirdHQ/atat#29]
`+CWMODE_CUR: 1` parses correctly while `+CWMODE_CUR:1` fails with `EofWhileParsingList`.

The problem seems to be caused by https://github.com/BlackbirdHQ/atat/blob/master/serde_at/src/de/mod.rs#L482. If I remove it both versions parse correctly.

~However, I noticed that for the ublox chips responses with multiple parameters are surrounded by `()` so `eat_char` is required for that.~ I misread that.

**Comment by MathiasKoch** [comment]
I believe you are right in your fix. I think that `eat_char` might have been a leftover from `serde_json_core` where i started of with the serde crate. 
There is still a bit of json parse leftovers thats unused in the serde_at crate. 
That is also why #14 is still an issue. 

Good catch.. I have pushed a fix
