### ISSUE TITLE
[RFC] Change logging to be defmt based

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/atat#57]
It should be possible to cut out all `core::fmt` bloat, for significant binary size wins, by switching out the `log` crate with `defmt` (https://github.com/knurling-rs/defmt)

**Pros:**
- Reduced binary size
- Faster logging
- Fits with `defmt` binaries

**Cons:**
- Not as flexible as `log` in general
- No logging on non-embedded targets

Perhaps it would be possible to make a wrapper that lets users choose between `log` and `defmt` at compile time?

**Comment by dbrgn** [comment]
There's also [ufmt](https://docs.rs/ufmt/0.1.0/ufmt/), but I assume if defmt is newer, it must have some advantages.

**Comment by MathiasKoch** [comment]
It has the obvious advantage of doing formatting on host-side, so it has a MUCH lower runtime overhead.

**Comment by dbrgn** [comment]
Ahh, I should have looked at it more closely... That is a great approach and saves some of the headaches I've been having with logging :)

**Comment by MathiasKoch** [comment]
Yup, it should actually allow logging stuff like incoming data in realtime, without much of a performance loss.

**Comment by dbrgn** [comment]
Maybe we could provide wrappers for the macros that log to either defmt or ufmt, depending on cargo flags.

**Comment by MathiasKoch** [comment]
That sounds like the correct approach
