### ISSUE TITLE
Docs: Does the driver! macro still exist?

### ISSUE THREAD

**Issue by mon** [BlackbirdHQ/atat#59]
Import fails and I can't seem to find it in the atat source - should I create a Client manually?

**Comment by MathiasKoch** [comment]
Hi @mon 

Yes, sorry for the back and forth of the initialization. Yes, you have to crate the Client manually. You can find an example here: https://github.com/BlackbirdHQ/atat/blob/master/atat/examples/rtic.rs

I will update the docs right away. Apparently they slipped by my review before releasing.

**Comment by mon** [comment]
Great! All going well I should have a working example for getting the IMEI off a sim card using the `linux_embedded_hal` early next week!

**Comment by MathiasKoch** [comment]
Cool!

This might be of help for you: https://github.com/BlackbirdHQ/ublox-cellular-rs/tree/master/examples
