### ISSUE TITLE
Crate name

### ISSUE THREAD

**Issue by dbrgn** [BlackbirdHQ/atat#8]
The crate name is a bit confusing since someone [is blocking the `at` name on crates.io](https://crates.io/crates/at). The fact that you're aliasing `at_rs as at` in the examples doesn't help either :slightly_smiling_face: 

What about renaming it to `atat` in reference to [AT-AT](https://starwars.fandom.com/wiki/All_Terrain_Armored_Transport)? Star wars references already [have some tradition in Rust crates](https://github.com/sfackler/r2d2). The name is short and still available on crates.io.

AT-AT could also be made into a nice logo :)

**Comment by MathiasKoch** [comment]
I have no strong feelings regarding the naming of the crate, so i'm up for it.

You know, the hardest thing in software development is naming things ;)

Would you maybe open a PR changing stuff? Then i will see if i can work out how to change the crates.io.. Yank and publish on the new name?

**Comment by tl8roy** [comment]
Probably a good thing I saw this as I named my project ATAT. I'll let you have it on crates.io and merge my work into yours

**Comment by dbrgn** [comment]
> Probably a good thing I saw this as I named my project ATAT-

:joy: 

Another idea I had was "Attila", in case someone wants to name a crate after a gory warlord :slightly_smiling_face:
