### ISSUE TITLE
In "basic usage example", call digest() instead of parse_at()

### ISSUE THREAD

**Issue by DrTobe** [BlackbirdHQ/atat#85]
Hi, is it possible that in the [basic usage example](https://github.com/BlackbirdHQ/atat/blob/master/atat/src/lib.rs#L194)
```Rust
#[interrupt]
fn TIM7() {
    let ingress = unsafe { INGRESS.as_mut().unwrap() };
    ingress.parse_at();
}
```
it should be
```Rust
    ...
    ingress.digest();
    ...
```
instead?

**Comment by MathiasKoch** [comment]
It looks like you are absolutely right.

Guess that is the downside to having it marked as `ignore` in doc-tests. 
If you find the time, a PR would be very welcomed :)
