### ISSUE TITLE
Cannot compile the example in the project

### ISSUE THREAD

**Issue by apeng2012** [BlackbirdHQ/atat#99]
$ cargo build --example rtic
   Compiling atat v0.11.1 (C:\Users\x\tmp\atat\atat)
error[E0433]: failed to resolve: use of undeclared crate or module `hal`
  --> atat\examples\rtic.rs:23:16
   |
23 | #[app(device = hal::pac, peripherals = true)]
   |                ^^^ use of undeclared crate or module `hal`

error[E0423]: expected function, tuple struct or tuple variant, found struct `Queue`
  --> atat\examples\rtic.rs:32:47
   |
32 |         static mut RES_QUEUE: ResQueue<256> = Queue(heapless::i::Queue::u8());
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |

rustc 1.53.0 (53cb7b09b 2021-06-17)
cargo 1.53.0 (4369396ce 2021-04-27)

**Comment by MathiasKoch** [comment]
Sorry about that.

It should be fixed by #100 

Will merge it as soon as it clears CI
